version: "3.3"

services:
    traefik:
        image: "traefik:2.3"
        container_name: "traefik"
        command:
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            # - "--entrypoints.web.address=:80"
            - "--entrypoints.websecure.address=:443"
            - "--log.level=DEBUG" # DEBUG, PANIC, FATAL, ERROR, WARN, INFO
            - "--log.filePath=/logs/traefik.log"
            - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
            # - "--certificatesresolvers.myresolver.acme.email=test@example.com"
            - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "./logs/:/logs/"

    frontend:
        image: starting-page-frontend
        container_name: "frontend"
        ports:
            - "3000:80"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.frontend.rule=Host(`${FRONTEND_DOMAIN}`)"
            - "traefik.http.routers.frontend.entrypoints=websecure"
            - "traefik.http.routers.whoami.tls.certresolver=myresolver"

    backend:
        image: starting-page-backend
        container_name: "backend"
        volumes:
            - ./database:/App/database
        ports:
            - "8000:80"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.backend.rule=Host(`${BACKEND_DOMAIN}`)"
            - "traefik.http.routers.backend.entrypoints=websecure"
            - "traefik.http.routers.whoami.tls.certresolver=myresolver"
