# Generated by Django 3.1 on 2020-08-28 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0003_bookmarks_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmarks',
            name='owner',
        ),
    ]
